### ISSUE TITLE
Implement temperature reading for AUX thermistor

### ISSUE THREAD

**Issue by rowanG077** [odriverobotics/ODrive#425]
When implement motor thermistor support I noticed there is a thermistor at the AUX FETs that is not used in the code (or maybe I'm blind). It would be great if we start reading out this thermistor as well.

**Comment by samuelsadok** [comment]
Yes that thermistor is unused. You can add code to read out this thermistor if you want but when it comes to acting on it things become a bit tricky.

We can't simply reduce brake resistor current if the AUX fets get too hot because that would mean that excess power is sunk into the power supply (which can destroy the PS or the ODrive or both).
Instead we'd need to provide the motor(s) with feedback that they need to reduce their negative current but not their positive current.

Before we add too much complex special purpose code I'd prefer to think about something like a generalized power solver which attempts to satisfy a prioritized list of constraints of all involved components (motors, brake resistor, power supply).

Maybe @madcowswe has an opinion on this.

**Comment by Wetmelon** [comment]
Hi @rowanG077, we're going to harden the v3 firmware as-is without this feature.  We always welcome well-tested PRs.
