### ISSUE TITLE
UART communication from Arduino to ODrive delay

### ISSUE THREAD

**Issue by Peter-haotian-cui** [odriverobotics/ODrive#428]
Hi, 
I'm using a stm32duino to communicate with ODrive and found a large delay to get a response (almost 1ms). The stm32 UART baudrate is set to 1Mbps, and using a self build ODrive with the same baudrate. Because I want to have a high frequency control (>500Hz), this 1ms delay is too much for my application. Does anyone knows about the reason and how to reduce the response delay.
![!Screenshot_2020-05-30-13-05-52](https://user-images.githubusercontent.com/38802432/85207049-c0b80200-b358-11ea-8a62-09da2d355b62.png)

Thanks!

**Comment by samuelsadok** [comment]
That might be because of this delay: https://github.com/madcowswe/ODrive/blob/master/Firmware/communication/interface_uart.cpp#L89

This delay exists because otherwise the loop would be a busy spin and starve other threads (such as motor control). There's a PR #393 which changes the UART code to use the RX interrupt instead of polling, maybe this fixes your issue.

**Comment by samuelsadok** [comment]
I'm gonna close this now that we have an increased polling frequency but if it's still an issue feel free to reopen.

**Comment by EMHacker-alt** [comment]
This is great !!!
