### ISSUE TITLE
ControlLoop_IRQHandler  use OTG_HS_IRQHandler as control process, how to explain this meaning, and how OTG_HS_IRQHandler work?

### ISSUE THREAD

**Issue by fisher1981** [odriverobotics/ODrive#566]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samuelsadok** [comment]
The name OTG_HS_IRQHandler is distracting because we don't actually use the OTG_HS peripheral, therefore we use macrose to rename it.

We trigger this interrupt line from software to run a control loop iteration. The software trigger happens in the TIM8 update ISR (`TIM8_UP_TIM13_IRQHandler`).

The reason for this design is that the control loop must run at medium interrupt context (higher than communication interrupts) and triggered by every second TIM8 interrupt, so it cannot be part of the TIM8 interrupt handler itself.
