### ISSUE TITLE
Add open loop waveform generation like vesc's openloop_duty

### ISSUE THREAD

**Issue by Kezii** [odriverobotics/ODrive#576]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to create an open loop waveform like vesc's `foc_openloop` and `foc_openloop_duty` commands

**Describe the solution you'd like**
A command like vesc's 
```
foc_openloop [current] [erpm]
  Create an open loop rotating current vector.
foc_openloop_duty [duty] [erpm]
  Create an open loop rotating voltage vector.
```

**Describe alternatives you've considered**
¯\\_(ツ)_/¯

**Additional context**
¯\\_(ツ)_/¯

**Comment by Wetmelon** [comment]
Hi @Kezii, this is called AXIS_STATE_LOCKIN_SPIN in ODrive.    You can configure the lockin spin here https://docs.odriverobotics.com/api/odrive.axis.lockinconfig

If you'd like to use volts instead of amps, you can set your motor to GIMBAL mode (in which case `current` changes units to volts)

Feel free to ask on Discourse or Discord if you would like help configuring it for your use-case.
