### ISSUE TITLE
Absolute encoder over SPI/SSI

### ISSUE THREAD

**Issue by madcowswe** [odriverobotics/ODrive#66]
We want asynchronous: Simple fire and check complete flag and read from register later if the encoder value is a single frame, DMA if not. 16bit single frame should be fine for the vast majority of SPI/SSI encoders.

We also want it to be triggered at a very defined time. If possible we want either the TIM1 (or 8) to hardware trigger the transfer, or we need to manually trigger it at the very beginning of the adc_pwm_cb code, to reduce jitter

**Comment by Wetmelon** [comment]
Per discourse discussion [here](https://discourse.odriverobotics.com/t/suggestions-for-a-new-encoder/319/4) the AMT10x series are being tested.  CUI also makes a very similar AMT20x series, which is essentially a 10-bit AMT10x with an additional 12-bit absolute encoder accessible over SPI.  I'm going to grab one of these for testing purposes.

There is also the [CTR Electronics SRX Magnetic Encoder](http://www.ctr-electronics.com/downloads/pdf/Magnetic%20Encoder%20User's%20Guide.pdf), which is what's used in the [VersaPlanetary Integrated Encoder](https://www.vexrobotics.com/vexpro/motors-electronics/encoders/217-5046.html).  This is a "1024CPR" (unsure if it's actually 1024 ppr or cpr) incremental encoder with an additional 244Hz PWM signal for absolute positioning.  Because of the simple integration with the VersaPlanetary gearbox, this might also be a good option.
